version: '3.8'

services:
  # MySQL
  mysql:
    image: mysql:latest
    container_name: aromio
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: aromio
      MYSQL_USER: eniemed
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  # PHPMyAdmin
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    ports:
      - "8081:80"
    depends_on:
      - mysql
    volumes:
      - phpmyadmin_data:/sessions

volumes:
  mysql_data:
  phpmyadmin_data: